version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'doctorado'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'doctorado'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password123456'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3310:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  doctorado-web-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://doctorado:doctorado1234@db:5432/doctorado

# Names our volume
volumes:
  my-db:
