version: '3.9'
services:
  db:
    image: 'postgres:13'
    restart: always
    # command: postgres -c log_statement='all' -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c log_filename='postgresql-%Y-%m-%d_%H%M%S.log'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=doctorado
      - POSTGRES_PASSWORD=doctorado1234
      - POSTGRES_DB=doctorado
      # volumes:
      # - ./logs:/logs
